spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:583667448214-n4shjocs2gbufthb037mcepgjechb5kg.apps.googleusercontent.com
            client-secret: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
