
version: "3"

services:

  db:
    image: mysql:8

    container_name: organized-mysql

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: "organized"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - /Users/hbjk/Desktop/ALL_MINE/organized/docker/volumeForMySql